<?php

require_once dirname(__FILE__) . '/../../../../../../../root/assets/lib/decorator/site/footer.class.php';

/**
 * Test class for Footer_Site_Decorator.
 * Generated by PHPUnit on 2012-03-29 at 23:26:46.
 */
class Footer_Site_DecoratorTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Footer_Site_Decorator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Footer_Site_Decorator;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @test
     */
    public function render_noRawFlag_encodesResult() {
        $this->object->add_inner('&');
        $this->assertContains('&amp;', $this->object->render());
    }

    /**
     * @test
     */
    public function render_rawFlagTrue_doesNotEncodesResult() {
        $this->object->add_inner('&');
        $this->assertNotContains('&amp;', $this->object->render(true));
    }

    /**
     * @test
     */
    public function render_rawFlagFalse_doesNotEncodesResult() {
        $this->object->add_inner('&');
        $this->assertContains('&amp;', $this->object->render(false));
    }

}

